[build]
  command = "make build"
  publish = "_build"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/trove.jsonl"
  [headers.values]
    Cache-Control = "max-age=60"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
